package com.eventlens.service.impl;

import com.eventlens.dto.ReportSummaryDTO;
import com.eventlens.enums.Role;
import com.eventlens.repository.BookingRepository;
import com.eventlens.repository.PaymentRepository;
import com.eventlens.repository.UserRepository;
import com.eventlens.service.ReportService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.eventlens.enums.BookingStatus;
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.lowagie.text.pdf.draw.LineSeparator;

import jakarta.servlet.http.HttpServletResponse;

import java.awt.Color;
import java.io.IOException;
import java.util.List;

import com.eventlens.entity.Booking;

@Service
public class ReportServiceImpl implements ReportService {

    @Autowired
    private BookingRepository bookingRepository;

    @Autowired
    private PaymentRepository paymentRepository;

    @Autowired
    private UserRepository userRepository;

    @Override
    public ReportSummaryDTO getSummaryReport() {

        ReportSummaryDTO report = new ReportSummaryDTO();

        report.setTotalBookings(
                bookingRepository.count()
        );
        report.setCompletedBookings(
                bookingRepository.countByStatus(BookingStatus.COMPLETED)
        );

        report.setCancelledBookings(
                bookingRepository.countByStatus(BookingStatus.CANCELLED)
        );

        report.setTotalCustomers(
                userRepository.countByRole(Role.CUSTOMER)
        );

        long providers =
                userRepository.countByRole(Role.PHOTOGRAPHER)
                        + userRepository.countByRole(Role.VIDEOGRAPHER);

        report.setTotalProviders(providers);

        Double revenue = paymentRepository.getTotalRevenue();

        report.setTotalRevenue(
                revenue == null ? 0.0 : revenue
        );

        return report;
    }

    @Override
    public void generateBookingReport(HttpServletResponse response)
            throws IOException {

        response.setContentType("application/pdf");

        Document document = new Document(PageSize.A4);

        PdfWriter.getInstance(document, response.getOutputStream());

        document.open();

        Image logo = Image.getInstance(
                "src/main/resources/static/images/eventlens-logo.png"
        );

        logo.scaleToFit(80,80);

        logo.setAlignment(Image.ALIGN_CENTER);

        document.add(logo);


        Font companyFont =
                new Font(Font.HELVETICA, 22, Font.BOLD, new Color(33,37,41));

        Font subtitleFont =
                new Font(Font.HELVETICA, 12, Font.NORMAL, Color.GRAY);

        Font reportFont =
                new Font(Font.HELVETICA, 18, Font.BOLD, new Color(13,110,253));

        Font infoFont =
                new Font(Font.HELVETICA, 11, Font.NORMAL);

        Paragraph company =
                new Paragraph("EVENTLENS", companyFont);

        company.setAlignment(Element.ALIGN_CENTER);

        document.add(company);

        Paragraph subtitle =
                new Paragraph(
                        "Photography & Videography Booking Platform",
                        subtitleFont
                );

        subtitle.setAlignment(Element.ALIGN_CENTER);

        document.add(subtitle);

        document.add(new Paragraph(" "));

        Paragraph report =
                new Paragraph("BOOKING REPORT", reportFont);

        report.setAlignment(Element.ALIGN_CENTER);

        document.add(report);

        document.add(new Paragraph(" "));

        document.add(new Paragraph(
                "Generated Date : " + java.time.LocalDate.now(),
                infoFont
        ));

        document.add(new Paragraph(
                "Generated Time : " + java.time.LocalTime.now().withNano(0),
                infoFont
        ));

        document.add(new Paragraph(
                "Generated By : Administrator",
                infoFont
        ));

        document.add(new Paragraph(" "));

        LineSeparator line = new LineSeparator();

        line.setLineColor(new Color(13,110,253));

        document.add(line);

        document.add(new Paragraph(" "));

        PdfPTable summary = new PdfPTable(2);

        summary.setWidthPercentage(50);

        summary.addCell("Total Bookings");

        summary.addCell(String.valueOf(
                bookingRepository.count()
        ));

        summary.addCell("Completed");

        summary.addCell(String.valueOf(
                bookingRepository.countByStatus(
                        BookingStatus.COMPLETED
                )
        ));

        summary.addCell("Cancelled");

        summary.addCell(String.valueOf(
                bookingRepository.countByStatus(
                        BookingStatus.CANCELLED
                )
        ));

        document.add(summary);

        document.add(new Paragraph(" "));

        PdfPTable table = new PdfPTable(5);

        table.setWidthPercentage(100);

        table.setWidths(new float[]{1.2f,3,3,2,2});

        addHeader(table,"ID");
        addHeader(table,"Customer");
        addHeader(table,"Provider");
        addHeader(table,"Date");
        addHeader(table,"Status");

        List<Booking> bookings = bookingRepository.findAll();

        for(Booking b : bookings){

            table.addCell(String.valueOf(b.getId()));

            table.addCell(b.getCustomer().getName());

            table.addCell(b.getServiceProvider().getName());

            table.addCell(String.valueOf(b.getEventDate()));

            table.addCell(String.valueOf(b.getStatus()));

        }

        document.add(table);

        document.close();

    }

    private void addHeader(PdfPTable table, String text) {

        PdfPCell cell = new PdfPCell();

        cell.setPhrase(new Phrase(
                text,
                new Font(Font.HELVETICA, 12, Font.BOLD, Color.WHITE)
        ));

        cell.setBackgroundColor(Color.DARK_GRAY);

        cell.setHorizontalAlignment(Element.ALIGN_CENTER);

        cell.setPadding(8);

        table.addCell(cell);

    }

    @Override
    public void generateRevenueReport(HttpServletResponse response)
            throws IOException {

        response.setContentType("application/pdf");

        Document document = new Document(PageSize.A4);

        PdfWriter.getInstance(document, response.getOutputStream());

        document.open();

        Image logo = Image.getInstance(
                "src/main/resources/static/images/eventlens-logo.png"
        );

        logo.scaleToFit(80,80);

        logo.setAlignment(Image.ALIGN_CENTER);

        document.add(logo);

        // ================= HEADER =================

        Font companyFont =
                new Font(Font.HELVETICA, 22, Font.BOLD, new Color(33,37,41));

        Font subtitleFont =
                new Font(Font.HELVETICA, 12, Font.NORMAL, Color.GRAY);

        Font reportFont =
                new Font(Font.HELVETICA, 18, Font.BOLD, new Color(13,110,253));

        Font infoFont =
                new Font(Font.HELVETICA, 11, Font.NORMAL);

        Paragraph company =
                new Paragraph("EVENTLENS", companyFont);

        company.setAlignment(Element.ALIGN_CENTER);

        document.add(company);

        Paragraph subtitle =
                new Paragraph(
                        "Photography & Videography Booking Platform",
                        subtitleFont
                );

        subtitle.setAlignment(Element.ALIGN_CENTER);

        document.add(subtitle);

        document.add(new Paragraph(" "));

        Paragraph report =
                new Paragraph("REVENUE REPORT", reportFont);

        report.setAlignment(Element.ALIGN_CENTER);

        document.add(report);

        document.add(new Paragraph(" "));

        document.add(new Paragraph(
                "Generated Date : " + java.time.LocalDate.now(),
                infoFont
        ));

        document.add(new Paragraph(
                "Generated Time : " + java.time.LocalTime.now().withNano(0),
                infoFont
        ));

        document.add(new Paragraph(
                "Generated By : Administrator",
                infoFont
        ));

        document.add(new Paragraph(" "));

        LineSeparator line = new LineSeparator();

        line.setLineColor(new Color(13,110,253));

        document.add(line);

        document.add(new Paragraph(" "));



        document.add(new Paragraph(
                "Total Revenue : Rs. " +
                        paymentRepository.getTotalRevenue(),
                infoFont
        ));

        document.add(new Paragraph(
                "Successful Payments : " +
                        paymentRepository.countByStatus(
                                com.eventlens.enums.PaymentStatus.SUCCESS
                        ),
                infoFont
        ));

        document.add(new Paragraph(
                "Pending Payments : " +
                        paymentRepository.countByStatus(
                                com.eventlens.enums.PaymentStatus.PENDING
                        ),
                infoFont
        ));

        document.close();
    }
    @Override
    public void generateCustomerReport(HttpServletResponse response)
            throws IOException {

        response.setContentType("application/pdf");

        Document document = new Document(PageSize.A4);

        PdfWriter.getInstance(document, response.getOutputStream());

        document.open();

        Image logo = Image.getInstance(
                "src/main/resources/static/images/eventlens-logo.png"
        );

        logo.scaleToFit(80,80);

        logo.setAlignment(Image.ALIGN_CENTER);

        document.add(logo);

        // ================= HEADER =================

        Font companyFont =
                new Font(Font.HELVETICA, 22, Font.BOLD, new Color(33,37,41));

        Font subtitleFont =
                new Font(Font.HELVETICA, 12, Font.NORMAL, Color.GRAY);

        Font reportFont =
                new Font(Font.HELVETICA, 18, Font.BOLD, new Color(13,110,253));

        Font infoFont =
                new Font(Font.HELVETICA, 11, Font.NORMAL);

        Paragraph company =
                new Paragraph("EVENTLENS", companyFont);

        company.setAlignment(Element.ALIGN_CENTER);

        document.add(company);

        Paragraph subtitle =
                new Paragraph(
                        "Photography & Videography Booking Platform",
                        subtitleFont
                );

        subtitle.setAlignment(Element.ALIGN_CENTER);

        document.add(subtitle);

        document.add(new Paragraph(" "));

        Paragraph report =
                new Paragraph("CUSTOMER REPORT", reportFont);

        report.setAlignment(Element.ALIGN_CENTER);

        document.add(report);

        document.add(new Paragraph(" "));

        document.add(new Paragraph(
                "Generated Date : " + java.time.LocalDate.now(),
                infoFont
        ));

        document.add(new Paragraph(
                "Generated Time : " + java.time.LocalTime.now().withNano(0),
                infoFont
        ));

        document.add(new Paragraph(
                "Generated By : Administrator",
                infoFont
        ));

        document.add(new Paragraph(" "));

        LineSeparator line = new LineSeparator();

        line.setLineColor(new Color(13,110,253));

        document.add(line);

        document.add(new Paragraph(" "));

        PdfPTable table = new PdfPTable(3);

        table.setWidthPercentage(100);

        table.setWidths(new float[]{1f,3f,4f});

        addHeader(table,"ID");
        addHeader(table,"Customer");
        addHeader(table,"Email");

        userRepository.findAll()

                .stream()

                .filter(u -> u.getRole() == Role.CUSTOMER)

                .forEach(u -> {

                    table.addCell(String.valueOf(u.getId()));

                    table.addCell(u.getName());

                    table.addCell(u.getEmail());

                });

        document.add(table);

        document.add(new Paragraph(" "));

        document.add(new Paragraph(
                "Total Customers : "
                        + userRepository.countByRole(Role.CUSTOMER),
                infoFont
        ));

        document.close();
    }


}